version: "3.7"
services:
  oenb-api:
    build: 
      context: ../../apps/OndeEstouNoBrasil.Web.API/.
      dockerfile: Dockerfile
    ports: 
      - 7002:80
    environment: 
      - MAP_TOKEN=

  oenb-spa:
    build: ../../uis/OndeEstouNoBrasil.Web.SPA/.
    restart: always
    depends_on:
      - oenb-api
    environment:
      API: "http://oenb-api:7002"
    ports:
      - 7003:80