version: '3'
services:
  
  pmc-api:
    build: ../../apps/Palavras.Web.API/.
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
    - 7004:80
    
  pmc-schedule:
    build: ../../apps/Palavras.Background.ETL/.
    restart: always
    depends_on:
      - pmc-api
    environment:
      TZ: "America/Sao_Paulo"
      Token: "SECRET"
      
  pmc-spa:
    build: ../../uis/Palavras.Web.SPA/.
    restart: always
    depends_on:
      - pmc-api
    ports:
      - 7005:80
    