version: '3'
services:
  
  pmc-api:
    build: ../../apps/Palavras.Web.API/.
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
    - 5001:80
    
  pmc-schedule:
    build: ../../apps/Palavras.Background.ETL/.
    restart: always
    depends_on:
      - pmc-api
    environment:
      TZ: "America/Sao_Paulo"
      Token: "SECRET"
