version: '3.5'

services:
  cpz-app:
    build:
      context: '../../apps/CompraPeloZap.Web.APP/'
      args:
        uid: 1000
    container_name: cpz-app
    ports:
      - 8084:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - DB_HOST=192.168.1.7
      - DB_PORT=3306
      - DB_DATABASE=shop
      - DB_USERNAME=root
      - DB_PASSWORD=qwerty
