version: "3.7"
services:
  app:
    build:
      context:  ../../apps/Amapa-Lanches/.
      dockerfile: Dockerfile
    image: apl
    container_name: apl-app
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      - connectionString=mysql:host=192.168.1.7;dbname=apl;charset=utf8
      - login=root
      - senha=qwerty