version: '3'
services:
  mysql:
    restart: unless-stopped
    image: mysql:latest
    container_name: mysql-production
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: db
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
volumes:
  dbdata:
